language: node_js

node_js:
    - "8.11.1"
    - "9.11.1"
    - "10.1.0"

before_script:
    - "npm install"

script:
    - "npm run test"

after_script:
    - "echo ${?}"

branches:
    only:
        - "master"

