language: node_js

node_js:
    - "6.14.3"
    - "7.10.1"
    - "8.11.4"
    - "9.11.2"
    - "10.9.0"

before_script:
    - "npm install"

script:
    - "npm run test"

after_script:

#branches:
#    only:
#        - "master"
