language: node_js
# ---------------
node_js:
    - "6.16.0"
    - "8.15.0"
    - "10.15.1"
    - "11.9.0"
# ---------------
before_script:
    - "npm install"
# ---------------
script:
    - "npm run test"
# ---------------
after_script:
# ---------------
#branches:
#    only:
#        - "master"
